In [6]:
import torch

In [7]:
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2
print(x)
print(y)


tensor(2., requires_grad=True)
tensor(4., grad_fn=<PowBackward0>)


In [8]:
y.backward()
print(x.grad)

tensor(4.)


In [13]:
import math

def dz_dx(x):
    return 2 * x * math.cos(x ** 2)

print(dz_dx(5.0))

9.912028118634735


In [10]:
x = torch.tensor(5.0, requires_grad=True)
y = x ** 2

z = torch.sin(y)
print(x)
print(y)
print(z)

z.backward()
print(x.grad)

tensor(5., requires_grad=True)
tensor(25., grad_fn=<PowBackward0>)
tensor(-0.1324, grad_fn=<SinBackward0>)
tensor(9.9120)


In [14]:
import torch

x = torch.tensor(6.7)
y = torch.tensor(0.0)

w = torch.tensor(1.0)
b = torch.tensor(0.0)

In [ ]:
#loss = binary_cross_entropy(prediction, target)
def binary_cross_entropy(prediction, target):
    epsilon = 1e-8
    prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
    return - (target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction))

In [17]:
#forward pass
z = w * x + b
y_pred = torch.sigmoid(z)

loss = binary_cross_entropy(y_pred, y)
print(loss)

tensor(6.7012)


In [18]:
#derivatives
dloss_dy_pred = (y_pred - y) / (y_pred * (1 - y_pred))

dy_pred_dz = y_pred * (1 - y_pred)
dz_dw = x
dz_db = 1.0

dloss_dw = dloss_dy_pred * dy_pred_dz * dz_dw
dloss_db = dloss_dy_pred * dy_pred_dz * dz_db

In [19]:
print(f'manual dloss_dw: {dloss_dw.item()}')
print(f'manual dloss_db: {dloss_db.item()}')

manual dloss_dw: 6.691762447357178
manual dloss_db: 0.998770534992218


**using Autograd**

In [20]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

z = w * x + b
y_pred = torch.sigmoid(z)
loss = binary_cross_entropy(y_pred, y)
loss.backward()
print(f'autograd dloss_dw: {w.grad.item()}')
print(f'autograd dloss_db: {b.grad.item()}')

autograd dloss_dw: 6.6917619705200195
autograd dloss_db: 0.9987704753875732


In [22]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
y = x ** 2
z = y.sum()
z.backward()
print(x.grad)

tensor([2., 4., 6.])


In [23]:
x.requires_grad_(False)
print(x.grad)

tensor([2., 4., 6.])


In [ ]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
z = y * y * 3
out = z.mean()
print(out) 
out.backward()
print(x.grad) 


tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [28]:
d = x.detach()
print(d)


tensor([[1., 1.],
        [1., 1.]])


In [29]:
with torch.no_grad():
    y = x + 2
    print(y)
    

tensor([[3., 3.],
        [3., 3.]])
