In [1]:
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [5]:
df = pd.read_csv('data/breast-cancer.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [6]:
print(df.shape)
print(type(df))
print(df.info())
print(df.isnull().sum())

(569, 32)
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non

In [13]:
df = df.drop(columns=['id'])
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [19]:
y = df['diagnosis'].map({'M': 1, 'B': 0})
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['diagnosis']), y, test_size=0.2, random_state=42)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)
print()
print(y.value_counts())

(455, 30) (455,)
(114, 30) (114,)

diagnosis
0    357
1    212
Name: count, dtype: int64


In [18]:
b_count = 0
m_count = 0
for i in y:
    if i == 0:
        b_count += 1
    else:
        m_count += 1

print(f'Benign count: {b_count}')
print(f'Malignant count: {m_count}')

Benign count: 357
Malignant count: 212


In [22]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print(X_train_scaled)
print(X_test_scaled)

[[-1.44075296 -0.43531947 -1.36208497 ...  0.9320124   2.09724217
   1.88645014]
 [ 1.97409619  1.73302577  2.09167167 ...  2.6989469   1.89116053
   2.49783848]
 [-1.39998202 -1.24962228 -1.34520926 ... -0.97023893  0.59760192
   0.0578942 ]
 ...
 [ 0.04880192 -0.55500086 -0.06512547 ... -1.23903365 -0.70863864
  -1.27145475]
 [-0.03896885  0.10207345 -0.03137406 ...  1.05001236  0.43432185
   1.21336207]
 [-0.54860557  0.31327591 -0.60350155 ... -0.61102866 -0.3345212
  -0.84628745]]
[[-0.46649743 -0.13728933 -0.44421138 ... -0.19435087  0.17275669
   0.20372995]
 [ 1.36536344  0.49866473  1.30551088 ...  0.99177862 -0.561211
  -1.00838949]
 [ 0.38006578  0.06921974  0.40410139 ...  0.57035018 -0.10783139
  -0.20629287]
 ...
 [-0.73547237 -0.99852603 -0.74138839 ... -0.27741059 -0.3820785
  -0.32408328]
 [ 0.02898271  2.0334026   0.0274851  ... -0.49027026 -1.60905688
  -0.33137507]
 [ 1.87216885  2.80077153  1.80354992 ...  0.7925579  -0.05868885
  -0.09467243]]


In [23]:
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
y_test_encoded = encoder.transform(y_test)
print(y_train_encoded)
print(y_test_encoded)

[0 1 0 0 0 1 0 0 0 1 0 1 1 0 0 1 1 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 1 1 0 1
 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0 0
 1 0 1 0 0 0 0 1 0 0 1 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0
 0 1 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 1 0 1 0 1 0 1 0 0 1 0 0 0 1 0 1 0 1 0 1
 0 0 1 0 0 0 0 1 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0
 1 1 0 0 1 0 1 1 1 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0 0 1 1 0 0 1 0 1 1 0 1 1
 0 0 1 1 1 0 0 0 0 1 0 1 1 1 1 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 1 0 0 1
 1 0 1 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 1 0 0 1 1 1 0
 0 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 1 0 1 1 0 0 1 0 1 1 0 1 1 0 0 1 0 1 0 0 1
 0 0 1 1 1 0 0 0 1 1 0 1 1 0 0 0 1 0 1 1 1 1 0 0 1 0 0 1 1 1 1 1 1 0 0 0 0
 0 0 0 1 1 1 1 0 0 0 0 1 0 1 0 0 0 0 0 1 1 1 0 0 1 0 0 1 1 1 1 0 0 1 1 0 0
 0 1 1 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 1 1 1
 0 1 1 0 1 0 0 0 0 1 0]
[0 1 1 0 0 1 1 1 0 0 0 1 0 1 0 1 0 0 0 1 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1
 

**numpy arrays to pytorch tensors**

In [28]:
X_train_tensor = torch.from_numpy(X_train_scaled)
X_test_tensor = torch.from_numpy(X_test_scaled)
y_train_tensor = torch.from_numpy(y_train_encoded)
y_test_tensor = torch.from_numpy(y_test_encoded)
print(X_train_tensor)
print(X_test_tensor)
print(y_train_tensor)
print(y_test_tensor)

tensor([[-1.4408, -0.4353, -1.3621,  ...,  0.9320,  2.0972,  1.8865],
        [ 1.9741,  1.7330,  2.0917,  ...,  2.6989,  1.8912,  2.4978],
        [-1.4000, -1.2496, -1.3452,  ..., -0.9702,  0.5976,  0.0579],
        ...,
        [ 0.0488, -0.5550, -0.0651,  ..., -1.2390, -0.7086, -1.2715],
        [-0.0390,  0.1021, -0.0314,  ...,  1.0500,  0.4343,  1.2134],
        [-0.5486,  0.3133, -0.6035,  ..., -0.6110, -0.3345, -0.8463]],
       dtype=torch.float64)
tensor([[-0.4665, -0.1373, -0.4442,  ..., -0.1944,  0.1728,  0.2037],
        [ 1.3654,  0.4987,  1.3055,  ...,  0.9918, -0.5612, -1.0084],
        [ 0.3801,  0.0692,  0.4041,  ...,  0.5704, -0.1078, -0.2063],
        ...,
        [-0.7355, -0.9985, -0.7414,  ..., -0.2774, -0.3821, -0.3241],
        [ 0.0290,  2.0334,  0.0275,  ..., -0.4903, -1.6091, -0.3314],
        [ 1.8722,  2.8008,  1.8035,  ...,  0.7926, -0.0587, -0.0947]],
       dtype=torch.float64)
tensor([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,

In [ ]:
class MySimpleNN():
    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.rand(1, dtype=torch.float64, requires_grad=True)

    def forward(self, X):
        return torch.sigmoid(X @ self.weights + self.bias)
    
    def loss_function(self, y_pred, y_true):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
        loss = -torch.mean(y_true * torch.log(y_pred) + (1 - y_true) * torch.log(1 - y_pred))
        return loss
    
    
    

In [48]:
learning_rate = 0.01
epochs = 1000


In [49]:
model = MySimpleNN(X_train_tensor)
for epoch in range(epochs):
    # Forward pass
    y_pred = model.forward(X_train_tensor)
    # print(y_pred)

    # Compute loss
    loss = model.loss_function(y_pred, y_train_tensor)
    # print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item()}")

    # Backward pass
    loss.backward()

    # Update weights and bias
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # Zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item()}")

Epoch 1/1000, Loss: 3.5338794254849764
Epoch 2/1000, Loss: 3.522095426358086
Epoch 3/1000, Loss: 3.510324275906463
Epoch 4/1000, Loss: 3.4985660768669185
Epoch 5/1000, Loss: 3.486820933529303
Epoch 6/1000, Loss: 3.47508895179606
Epoch 7/1000, Loss: 3.4633046237625904
Epoch 8/1000, Loss: 3.4514305558078817
Epoch 9/1000, Loss: 3.4395543229479166
Epoch 10/1000, Loss: 3.427415691053008
Epoch 11/1000, Loss: 3.4151521509925664
Epoch 12/1000, Loss: 3.4028870375895535
Epoch 13/1000, Loss: 3.3904749007659345
Epoch 14/1000, Loss: 3.378077959019689
Epoch 15/1000, Loss: 3.365696350096357
Epoch 16/1000, Loss: 3.353330214276197
Epoch 17/1000, Loss: 3.3409666976465484
Epoch 18/1000, Loss: 3.3284253716666075
Epoch 19/1000, Loss: 3.315900373002983
Epoch 20/1000, Loss: 3.303391857440225
Epoch 21/1000, Loss: 3.290899983736175
Epoch 22/1000, Loss: 3.2784021835138835
Epoch 23/1000, Loss: 3.2656796840674853
Epoch 24/1000, Loss: 3.252716149797837
Epoch 25/1000, Loss: 3.2394607075081088
Epoch 26/1000, Loss: 3

In [50]:
print(model.weights)
print(model.bias)

tensor([[-0.1260],
        [-0.2689],
        [-0.0729],
        [-0.1736],
        [-0.0121],
        [ 0.0453],
        [-0.1122],
        [ 0.1648],
        [-0.0955],
        [ 0.3119],
        [-0.2116],
        [-0.1302],
        [ 0.0250],
        [ 0.0609],
        [-0.0477],
        [ 0.1916],
        [ 0.1877],
        [ 0.0655],
        [ 0.2039],
        [-0.4204],
        [ 0.0631],
        [ 0.3866],
        [ 0.2639],
        [ 0.4703],
        [-0.0596],
        [-0.2097],
        [-0.1415],
        [-0.3450],
        [-0.1042],
        [ 0.2312]], dtype=torch.float64, requires_grad=True)
tensor([-0.3606], dtype=torch.float64, requires_grad=True)


In [54]:
with torch.no_grad():
    y_test_pred = model.forward(X_test_tensor)
    y_test_pred_labels = (y_test_pred >= 0.5).float()
    accuracy = (y_test_pred_labels.squeeze() == y_test_tensor).float().mean()
    print(f"Test Accuracy: {accuracy.item() * 100:.2f}%")

Test Accuracy: 59.65%
