In [2]:
# Create Model Class
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [7]:
# create Dataset
features = torch.rand(10, 5)

#create Model
model = Model(features.shape[1])
#OR
# model = Model(num_features=5)

# forward pass
# output = model.forward(features) # can do but not recommended
output = model(features)
print(output)

tensor([[0.6495],
        [0.5932],
        [0.5855],
        [0.6163],
        [0.4988],
        [0.5733],
        [0.5892],
        [0.5001],
        [0.6019],
        [0.6233]], grad_fn=<SigmoidBackward0>)


In [8]:
# show model weights
print(model.linear.weight)

Parameter containing:
tensor([[0.3066, 0.0647, 0.3963, 0.2559, 0.0483]], requires_grad=True)


In [11]:
from torchinfo import summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# NN with hidden layers

In [12]:
# Create Model Class
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

In [13]:
# create Dataset
features = torch.rand(10, 5)

#create Model
model = Model(features.shape[1])
#OR
# model = Model(num_features=5)

# forward pass
# output = model.forward(features) # can do but not recommended
output = model(features)
print(output)

tensor([[0.6341],
        [0.6626],
        [0.6399],
        [0.6522],
        [0.6772],
        [0.6676],
        [0.6586],
        [0.6437],
        [0.6533],
        [0.6117]], grad_fn=<SigmoidBackward0>)


In [14]:
model.linear1.weight

Parameter containing:
tensor([[ 0.2822,  0.3760, -0.2113,  0.3412, -0.2831],
        [ 0.0272, -0.2034,  0.1822,  0.3873,  0.2756],
        [ 0.3114,  0.0947,  0.3553, -0.0737,  0.1486]], requires_grad=True)

In [15]:
model.state_dict()

OrderedDict([('linear1.weight',
              tensor([[ 0.2822,  0.3760, -0.2113,  0.3412, -0.2831],
                      [ 0.0272, -0.2034,  0.1822,  0.3873,  0.2756],
                      [ 0.3114,  0.0947,  0.3553, -0.0737,  0.1486]])),
             ('linear1.bias', tensor([ 0.4245,  0.2597, -0.3921])),
             ('linear2.weight', tensor([[ 0.3435,  0.3550, -0.1830]])),
             ('linear2.bias', tensor([0.1588]))])

In [16]:
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Sequestial Container

In [18]:
# Create Model Class
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )

    def forward(self, features):
        out = self.network(features)
        return out

In [19]:
# create Dataset
features = torch.rand(10, 5)

#create Model
model = Model(features.shape[1])
#OR
# model = Model(num_features=5)

# forward pass
# output = model.forward(features) # can do but not recommended
output = model(features)
print(output)

tensor([[0.3921],
        [0.3923],
        [0.3923],
        [0.3922],
        [0.3923],
        [0.3923],
        [0.3923],
        [0.3923],
        [0.3923],
        [0.3922]], grad_fn=<SigmoidBackward0>)


In [20]:
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00